from flask import Flask, render_template, request

app = Flask(__name__)

# Sample student data
student_data = {
    "21EC461": {
    "name": "Aditya Ranjan",
    "course": "BE",
    "department": "ECE",
    "usn": "1va21ec001",
    "blood_group": "B +Ve",
    "phone_no": "+91 7676684851",
    "pp_no": "8861007268",
    "address": "S/o Pramod Kumar Ranjan., 8th Cross, Addiganahalli, Rajanjukunte, Bengaluru-560064",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC310": {
    "name": "Akash Bolegaon",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC002",
    "blood_group": "B +Ve",
    "phone_no": "+91 7975404435",
    "pp_no": "9449456123",
    "address": "# 12A, 4th Cross, Muneshwara Layout, Near Akshya Nursing Home, Yelahanka, Bengaluru - 560064",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC357": {
    "name": "Akash Nair A.",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC003",
    "blood_group": "O +Ve",
    "phone_no": "+91 6360212013",
    "pp_no": " 8970711951",
    "address": "# B-205, DS Max Skyscape, Rampura Cross, Bidrahalli [P], Bengaluru - 560049",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
    
},
"21EC217": {
    "name": "Akash Sanganna Harsoorker",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC004",
    "blood_group": "-",
    "phone_no": "+91 9901112800",
    "pp_no": "-",
    "address": "S/o Sanganna., Kaveri Nagar, Shaha Bazar, Kalburgi - 585101",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC168": {
    "name": "Amar Muttappa Karadigudda",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC005",
    "blood_group": "A +Ve",
    "phone_no": "+91 8123303580",
    "pp_no": "8884759061",
    "address": "S/o Muttappa S Karadigudd., Kakanur [P], Badami [T], Bagalkote [D] - 587155",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC436": {
    "name": "Ambika",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC006",
    "blood_group": "A +Ve",
    "phone_no": "+91  8123082640",
    "pp_no": "9845010994",
    "address": "D/o Jagadish K., Ward no 17, Near 40th Canal, Venkateshwara Nagar, Sindhanur, Raichur Dist-584128",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC128": {
    "name": "Ananya L.",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC007",
    "blood_group": "B +Ve",
    "phone_no": "+91 7406646373",
    "pp_no": "9886985042",
    "address": "D/o Lakshmaiah., Gejjigadahalli, Madhure [H], Doddaballapur [T], Bengaluru Rural - 561203",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC256": {
    "name": "Anika Shreya Prasad",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC008",
    "blood_group": "B +Ve",
    "phone_no": "+91 7892238685",
    "pp_no": "9845458628",
    "address": "# 38, 4th Cross, Kasturi Badavane, Rajagopalnagar, Peenya 2nd Stage, Bengaluru - 560058",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC449": {
    "name": "Ankitha R.",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC009",
    "blood_group": "O +Ve",
    "phone_no": "+91 9019954188",
    "pp_no": " 9986147512",
    "address": "# 1524, Kuchchappanapete, Doddaballapura-561203",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21EC366": {
    "name": "Bharat Raj P.",
    "course": "BE",
    "department": "ECE",
    "usn": "1VA21EC010",
    "blood_group": "O +Ve",
    "phone_no": "+91  6362958248",
    "pp_no": "9886801901",
    "address": "# 14, 1st Main, 3rd A-Cross, Nanjappa Layout, Vidyaranyapura, Bengaluru - 560097",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21IS290": {
    "name": "Aditya M. V.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS001",
    "blood_group": "O +Ve",
    "phone_no": "+91 9019862996",
    "pp_no": "9449813637",
    "address": "# 452, 20th Main, Judicial Layout, GKVK [P], Bengaluru - 560065",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21IS105": {
    "name": "Akash D.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS002",
    "blood_group": "O +Ve",
    "phone_no": "+91  8073187298",
    "pp_no": "9845980116",
    "address": "# 192, 9th Cross, Ring Road, Maruthi Nagar, Nagashettihalli, RMV Extn. 2nd Stage, Bengaluru-560094",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS114": {
    "name": "Amrutha M.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS03",
    "blood_group": "A +Ve",
    "phone_no": "+91 9845571009",
    "pp_no": "8722245018",
    "email" : "amrutham.21is@saividya.ac.in",
    "address": "# 24, I - C- Main, 5th Cross, 2nd Stage, AGB Colony, Mahalakshmipuram, Bengaluru-560086",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "9.3",
    "internship":"java , python",
    "miniproject":"movie recomdation",
    "Currentsemester" : "6th",
    "Joingdate" : "30-dec-2021",
    "proctor": "Asst.Prof Vidya Dept. of ISE",
    "proctoremail" : "vidya.ha@saividya.ac.in",
    "com" : "",

},
 "21IS265": {
    "name": "Anisha Gazi.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS004",
    "blood_group": "AB +Ve",
    "phone_no": "+91  8892580344",
    "pp_no": " 9741251776",
    "address": "# 105, 4th Cross, Ganesh Layout, MS Palya, Bengaluru - 560097",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS115": {
    "name": "Anushri Prasad R.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS005",
    "blood_group": "A +Ve",
    "phone_no": "+91 8296104205",
    "pp_no": "9945399342",
    "address": "Flat No. 108, KPT SLV Durga Apt., 8th A Cross, Nanjappa Layout, Vidyaranyapura, Bengaluru - 560097",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS222": {
    "name": "Arshiya Jabeen",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS006",
    "blood_group": "A +Ve",
    "phone_no": "+91 7676670066",
    "pp_no": "8867176636",
    "address": "Flat No. 263, Behind HRG, Taranagallu, Sanduru Tq, Bellary Dist - 583123",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS254": {
    "name": "Asrar Hussain",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS007",
    "blood_group": "O -Ve",
    "phone_no": "+91  7760239608",
    "pp_no": " 9945671492",
    "address": "# 11, Ahmed Manzu, 11th Cross, Basement Block, Ganganagar, R.T. Nagar, Bengaluru - 560032",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS401": {
    "name": "B. S. Kruthi",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS008",
    "blood_group": "O +Ve",
    "phone_no": "+91 7676387643",
    "pp_no": "-",
    "address": "# 109, 3rd Main, Ravikirloskar Layout, Chikkabidarekallu, Nagasandra [P], Bengaluru - 560073",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS023": {
    "name": "Binita Baral",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS009",
    "blood_group": "B +Ve",
    "phone_no": "+91 9019667898",
    "pp_no": " 9844992718",
    "address": "# 3G, KIADB Qtrs., Peenya Indl. Area, 1st Stage Peenya, Bengaluru - 560058",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21IS155": {
    "name": "Chandan V. S.",
    "course": "BE",
    "department": "ISE",
    "usn": "1VA21IS010",
    "blood_group": "B +Ve",
    "phone_no": "+91 9353170684",
    "pp_no": "7483517069",
    "address": "# 66, 2nd Cross, Near Singapura Bus Stop, Lakkappa Layout, Singapura, Bengaluru - 560097",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
 "21CS228": {
    "name": "Abhay Ram J.",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS001",
    "blood_group": "B +Ve",
    "phone_no": "+91 9353492824",
    "pp_no": "9380085050",
    "address": "# 46, Opp St. Philomenas Public School, Doddabyarkere Bachanna Layout, Bengaluru - 560089",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS069": {
    "name": "Aditya Kiran",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS002",
    "blood_group": "A +Ve",
    "phone_no": "+91 9886092893",
    "pp_no": "9844144680",
    "address": "# 188, 14th Cross, 3rd Phase, Girinagar, Bengaluru - 560085",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS411": {
    "name": "Ajay Chavan",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS003",
    "blood_group": "-",
    "phone_no": "+91  8669072848",
    "pp_no": "8208957742",
    "address": "S/o Tippesh Hanumant Chavan, Kalasapur, Gadag Dist - 582103",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS315": {
    "name": "Akash M.",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS004",
    "blood_group": "O +Ve",
    "phone_no": "+91 9148930214",
    "pp_no": " 9343243850",
    "address": "# 493, Doddaballapura Main Road, Rajanukunte, Bengaluru North - 560064",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS342": {
    "name": "Anurag Kumar",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS005",
    "blood_group": "O +Ve",
    "phone_no": "+91 9905509331",
    "pp_no": " 9931959951",
    "address": "S/o Sanjiv Sharma., New Area, Nathchak, Barh, Patna, Bihar - 803213",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS213": {
    "name": "Ashwini M. H.",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS006",
    "blood_group": "B +Ve",
    "phone_no": "+91  8660767640",
    "pp_no": "8073027635",
    "address": "# 807, NMIG B-TYBE, 13th Block, 5th Phase, Yelahanka New Town, Bengaluru - 560064",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS335": {
    "name": "Atharva Misra",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS007",
    "blood_group": "A +Ve",
    "phone_no": "+91  9219004079",
    "pp_no": " 998423000",
    "address": "S/o Vinay Misra., # 75, Ram Nagar Colony, [L.M.P] Uttarpradesh - 262701",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS021": {
    "name": "B. Kishore",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS008",
    "blood_group": "A +Ve",
    "phone_no": "+91 8431016907",
    "pp_no": "9901882719",
    "address": "# 20, 4th Cross, Harisiddegowda Layout, Chamanayakana Palya, Chikkabidarakallu, Bengaluru-560073",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS308": {
    "name": "B. Nasreen.",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS009",
    "blood_group": "A +Ve",
    "phone_no": "+91 6362140295",
    "pp_no": " 7019236952",
    "address": "# 46/B, Chavan Plot, Priyadasrshini Colony, Gokul Road, Hubballi - 580030",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
},
"21CS334": {
    "name": "B. Nuthan Vamshi Kumar",
    "course": "BE",
    "department": "CSE",
    "usn": "1VA21CS010",
    "blood_group": "-",
    "phone_no": "+91 7032917360",
    "pp_no": "9985495925",
    "address": "# 6/3, Begampurpet, Adoni, Kurnool, Andra Pradesh - 518301",
    "expiry_date": "31-AUG-2025",
    "cgpa" : "--",
    "internship":"--",
    "miniproject":"--",
    "Currentsemester" : "--",
    "Joingdate" : "--",
    "proctor": "--",
    "proctoremail" : "--",
    "email" : "--",
}
}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/result_page.html')
def result_page():
    code = request.args.get('code')
    return render_template('result.html', code=code)

@app.route('/personal.html')
def personal():
    code = request.args.get('code')
    if code:
        if code in student_data:
            student = student_data[code]
            return render_template('personal.html', student=student)
        else:
            return "Student not found", 404
    else:
        return "No code provided", 400

@app.route('/professional.html')
def professional():
    code = request.args.get('code')
    if code and code in student_data:
        student = student_data[code]
        return render_template('professional.html', student=student)
    else:
        return "Student not found", 404



@app.route('/submit', methods=['POST'])
def submit():
    global complaint_data
    complaint_data = request.form['complaint']
    return render_template('viewcom.html', complaint_data=complaint_data)



@app.route('/com.html')
def com():
    code = request.args.get('code')
    if code and code in student_data:
        student = student_data[code]
        return render_template('com.html', student=student)
    else:
        return "Student not found", 404

@app.route('/student_details.html')
def student_details():
    code = request.args.get('code')
    student = student_data.get(code)
    return render_template('student_details.html', student=student)

if __name__ == '__main__':
    app.run(debug=True)
